[package]
name = "server-r-agent-proto"
version = "0.1.1"
edition = "2021"
description = "Rust gRPC protocol definitions for server-agent communication"
license = "GPL-3.0"

[dependencies]
prost = "0.14"
tonic = "0.14"
tonic-prost = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"
